version: "3.7"

services:
  reactfront:
    container_name: reactv07
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  flask:
    build: ./flask
    ports:
      - "8000:8000"
    container_name: flaskv:versio02
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8000
    volumes:
      - ../:/app
      - ./db/:./Z_Django/Z_Vision/src/Usersdatabase.db
      #- ./db/:/my/sqlite/path/ # Here is the change
    command: pipenv run gunicorn --bind=0.0.0.0:8000 --reload app:app

  rasabot:
    build: ./rasa
    container_name: rasa
    restart: always
    ports:
      - “5000:5000”
